name: AnalisadorDePerfil

on:
  push:
    branches: [ main ]

jobs:
  build-e-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalação do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalação das dependências
        run: npm install

      - name: Compilação do TypeScript
        run: npx tsc

      - name: Implantação para o Github Pages
        uses: JamesIves/github-pages-deploy@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          destination: docs
